services:
  - type: web
    name: book-selling-platform
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        scope: runtime
        value: production
